Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['web'])->group(function () {
    Route::name('cms.')->group(function() {

        Route::get('/', 'Frontend\HomeController@index')->name('home');
        Route::get('jobs', 'Frontend\HomeController@jobs')->name('job');
        Route::get('jobs/{slug}', 'Frontend\HomeController@jobsDetail')->name('job.detail');
        Route::get('clients', 'Frontend\HomeController@client')->name('client');
        Route::get('/info', 'Frontend\HomeController@info')->name('info');
        Route::get('/info/{id}', 'Frontend\HomeController@infoDetail')->name('info.detail');
        Route::get('contact', 'Frontend\HomeController@contactUs')->name('contact');
        Route::get('video/show/{id}', 'Frontend\HomeController@videoShow')->name('video');
        Route::get('test', 'Frontend\HomeController@test')->name('test');
        Route::get('test-result', 'Frontend\HomeController@testResult')->name('test.result');

    });
});

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('cms')->group(function() {
            Route::name('job.')->group(function() {
                Route::get('jobs', 'JobController@index')->name('index')->middleware('permission:cms-jobs-list');
                Route::get('jobs/create', 'JobController@create')->name('create')->middleware('permission:cms-jobs-create');
                Route::post('jobs/create', 'JobController@store')->name('store')->middleware('permission:cms-jobs-create');
                Route::get('jobs/{id}/edit', 'JobController@edit')->name('edit')->middleware('permission:cms-jobs-edit');
                Route::patch('jobs/{id}', 'JobController@update')->name('update')->middleware('permission:cms-jobs-edit');
                Route::delete('jobs/{id}', 'JobController@destroy')->name('destroy')->middleware('permission:cms-jobs-delete');
            });
            Route::name('slider.')->group(function() {
                Route::get('sliders', 'SliderController@index')->name('index');
                Route::get('sliders/create', 'SliderController@create')->name('create');
                Route::post('sliders/create', 'SliderController@store')->name('store');
                Route::get('sliders/{id}/show', 'SliderController@show')->name('show');
                Route::get('sliders/{id}/edit', 'SliderController@edit')->name('edit');
                Route::patch('sliders/{id}', 'SliderController@update')->name('update');
                Route::delete('sliders/{id}', 'SliderController@destroy')->name('destroy');
            });
            Route::name('info.')->group(function() {
                Route::get('info', 'InfoController@index')->name('index');
                Route::get('info/create', 'InfoController@create')->name('create');
                Route::post('info/create', 'InfoController@store')->name('store');
                Route::get('info/{id}/show', 'InfoController@show')->name('show');
                Route::get('info/{id}/edit', 'InfoController@edit')->name('edit');
                Route::patch('info/{id}', 'InfoController@update')->name('update');
                Route::delete('info/{id}', 'InfoController@destroy')->name('destroy');
            });

            Route::name('video.')->group(function() {
                Route::get('videos', 'VideoController@index')->name('index');
                Route::get('videos/create', 'VideoController@create')->name('create');
                Route::post('videos/create', 'VideoController@store')->name('store');
                Route::get('videos/{id}/show', 'VideoController@show')->name('show');
                Route::get('videos/{id}/edit', 'VideoController@edit')->name('edit');
                Route::patch('videos/{id}', 'VideoController@update')->name('update');
                Route::delete('videos/{id}', 'VideoController@destroy')->name('destroy');
            });

            Route::name('about.')->group(function() {
                Route::get('about', 'AboutUsController@index')->name('index');
                Route::get('about/{id}/edit', 'AboutUsController@edit')->name('edit');
                Route::patch('about/{id}', 'AboutUsController@update')->name('update');
            });

            Route::name('service.')->group(function() {
                Route::get('service', 'ServiceController@index')->name('index');
                Route::get('service/create', 'ServiceController@create')->name('create');
                Route::post('service/create', 'ServiceController@store')->name('store');
                Route::get('service/{id}/show', 'ServiceController@show')->name('show');
                Route::get('service/{id}/edit', 'ServiceController@edit')->name('edit');
                Route::patch('service/{id}', 'ServiceController@update')->name('update');
                Route::delete('service/{id}', 'ServiceController@destroy')->name('destroy');
            });

            Route::name('client.')->group(function() {
                Route::get('client', 'ClientController@index')->name('index');
                Route::get('client/create', 'ClientController@create')->name('create');
                Route::post('client/create', 'ClientController@store')->name('store');
                Route::get('client/{id}/edit', 'ClientController@edit')->name('edit');
                Route::patch('client/{id}', 'ClientController@update')->name('update');
                Route::delete('client/{id}', 'ClientController@destroy')->name('destroy');
            });

            Route::name('contact.')->group(function() {
                Route::get('contact', 'ContactController@index')->name('index');
                Route::get('contact/create', 'ContactController@create')->name('create');
                Route::post('contact/create', 'ContactController@store')->name('store');
                Route::get('contact/{id}/show', 'ContactController@show')->name('show');
                Route::get('contact/{id}/edit', 'ContactController@edit')->name('edit');
                Route::patch('contact/{id}', 'ContactController@update')->name('update');
                Route::delete('contact/{id}', 'ContactController@destroy')->name('destroy');
            });

            Route::name('setting.')->group(function() {
                Route::get('settings', 'SettingsController@index')->name('index');
            });
        });
    });
});

Entities/Service.php
<?php

namespace Modules\CMS\Entities;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $table = 'cms_services';
    protected $fillable = [
        'title',
        'description',
        'image',
        'order',
        'is_active'
    ];
}

Http/Controllers/ServiceController.php
<?php

namespace Modules\CMS\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\CMS\Entities\Service;
use Illuminate\Support\Facades\Storage;

class ServiceController extends Controller
{
    protected $disk;

    public function __construct()
    {
        $this->disk = config('cms.disk');
    }
    
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $params['pageTitle']    = 'Services';
        $params['pageSubTitle'] = 'Index';
        $params['data']         = Service::all();
        return view('cms::services.index', $params);
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $params['pageTitle']    = 'Services';
        $params['pageSubTitle'] = 'Create';
        return view('cms::services.create', $params);
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        try {
            $data['title']      = trim($request->title);
            $data['description']= trim($request->description);
            $data['order']      = $request->order;
            $data['is_active']  = $request->is_active == 1 ? 1 : 0;

            if($request->hasFile('image')) {
                $fileExt    = strtolower($request->file('image')->getClientOriginalExtension());
                $fileName   = 'service-' . md5(date('Y-m-d').time()) . '.' . $fileExt;
                $data['image']   = $fileName;
                Storage::disk($this->disk)->put(
                    'cms/services/' . $fileName,
                    fopen($request->file('image'), 'r+'),
                    'public'
                );
            }

            Service::create($data);
            return redirect(route('service.index'))
				->with('success_message', trans('message.success_save'));
        } catch(\Exception $e) {
            return redirect(route('service.index'))
				->with('error_message', trans('message.error_save'));
        }
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show($id)
    {
        $params['pageTitle']    = 'Services';
        $params['pageSubTitle'] = 'Detail';
        $params['data']         = Service::findOrFail($id);
        return view('cms::services.show', $params);
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit($id)
    {
        $params['pageTitle']    = 'Services';
        $params['pageSubTitle'] = 'Edit';
        $params['data']         = Service::findOrFail($id);
        return view('cms::services.edit', $params);
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(Request $request, $id)
    {
        try {
            $service = Service::findOrFail($id);
            $data['title']      = trim($request->title);
            $data['description']= trim($request->description);
            $data['order']      = $request->order;
            $data['is_active']  = $request->is_active == 1 ? 1 : 0;

            if($request->hasFile('image')) {
                $fileExt    = strtolower($request->file('image')->getClientOriginalExtension());
                $fileName   = 'service-' . md5(date('Y-m-d').time()) . '.' . $fileExt;
                $data['image']   = $fileName;
                Storage::disk($this->disk)->put(
                    'cms/services/' . $fileName,
                    fopen($request->file('image'), 'r+'),
                    'public'
                );

                if(!empty($service->image)) {
                    Storage::disk('public')->delete('services/' . $service->image);
                }
            }

            $service->update($data);
            return redirect(route('service.index'))
				->with('success_message', trans('message.success_edit'));
        } catch(\Exception $e) {
            return redirect(route('service.index'))
				->with('error_message', trans('message.error_edit'));
        }
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy($id)
    {
        try {
            $data = Service::findOrFail($id);
            if(!empty($data->image)) {
                Storage::disk($this->disk)->delete('cms/services/' . $data->image);
            }
            $data->delete();
            return redirect(route('service.index'))
				->with('success_message', trans('message.success_delete'));
        } catch (\Exception $e) {
            return redirect(route('service.index'))
				->with('error_message', trans('message.error_delete'));
        }
    }
}

Resources/views/services/create.blade.php
@extends('cms::layouts.master')

@section('content')

    {!! Form::open([ 'route' => 'service.store', 'class' => 'form-horizontal', 'files' => true, 'autocomplete' => 'off' ]) !!}
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{!! $pageTitle !!}</h3>
                        <div class="box-tools pull-right">
                            <a class="btn btn-sm btn-danger" href="{!! route('service.index') !!}">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="title" class="col-sm-2 control-label">Title <span class="required">*</span></label>
                                    <div class="col-sm-8">
                                        {!! Form::text('title', null, [ 'class' => 'form-control', 'maxlength' => 100, 'required', 'autofocus']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="description" class="col-sm-2 control-label">Description <span class="required">*</span></label>
                                    <div class="col-sm-8">
                                        {!! Form::textarea('description', null, [ 'class' => 'form-control', 'id' => 'description', 'maxlength' => 5000, 'required']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="image" class="col-sm-2 control-label">Image <span class="required">*</span></label>
                                    <div class="col-sm-8">
                                        {!! Form::file('image', null, [ 'class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="order" class="col-sm-2 control-label">Order</label>
                                    <div class="col-sm-3">
                                        {!! Form::number('order', 0, [ 'class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="is_active" class="col-sm-2 control-label">Active? </label>
                                    <div class="col-sm-6">
                                        <div class="checkbox">
                                            <label>
                                                {!! Form::checkbox('is_active', true, true) !!} Yes
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="reset" class="btn btn-default">Cancel</button>
                        <button type="submit" class="btn btn-info pull-right">Save</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}

@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $("#description").wysihtml5();
        });
    </script>
@endsection

Resources/views/services/edit.blade.php
@extends('cms::layouts.master')

@section('content')

    {!! Form::open([ 'route' => ['service.update', $data->id], 'method' => 'patch', 'class' => 'form-horizontal', 'files' => true, 'autocomplete' => 'off' ]) !!}
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{!! $pageTitle !!}</h3>
                        <div class="box-tools pull-right">
                            <a class="btn btn-sm btn-danger" href="{!! route('service.index') !!}">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="title" class="col-sm-2 control-label">Title <span class="required">*</span></label>
                                    <div class="col-sm-8">
                                        {!! Form::text('title', $data->title, [ 'class' => 'form-control', 'maxlength' => 100, 'required', 'autofocus']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="description" class="col-sm-2 control-label">Description <span class="required">*</span></label>
                                    <div class="col-sm-8">
                                        {!! Form::textarea('description', $data->description, [ 'class' => 'form-control', 'id' => 'description', 'maxlength' => 5000, 'required']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="image" class="col-sm-2 control-label">Image <span class="required">*</span></label>
                                    <div class="col-sm-8">
                                        {!! Form::file('image', null, [ 'class' => 'form-control']) !!}
                                        @if(!empty($data->image))
                                        <br>
                                        <img src="{!! asset('storage/services/' . $data->image) !!}" style="max-width: 300px; border-radius: 10px" />
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="order" class="col-sm-2 control-label">Order</label>
                                    <div class="col-sm-3">
                                        {!! Form::number('order', $data->order, [ 'class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="is_active" class="col-sm-2 control-label">Active? </label>
                                    <div class="col-sm-6">
                                        <div class="checkbox">
                                            <label>
                                                {!! Form::checkbox('is_active', true, $data->is_active == true ? true : false) !!} Yes
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="reset" class="btn btn-default">Cancel</button>
                        <button type="submit" class="btn btn-info pull-right">Save</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}

@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $("#description").wysihtml5();
        });
    </script>
@endsection

Resources/views/services/index.blade.php
@extends('cms::layouts.master')

@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="box-tools pull-right">
                        {{-- @can('service-create') --}}
                        <a class="btn btn-sm btn-primary" href="{!! route('service.create') !!}">
                            <i class="fa fa-plus"></i> Service Baru
                        </a>
                        {{-- @endcan --}}
                    </div>
                </div>
                <div class="box-body" style="min-height: 520px">
                    <table id="grid-service" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th style="width: 5%">No.</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Status</th>
                                <th>Created</th>
                                <th class="text-center" style="width: 5%">
                                    <i class="fa fa-navicon"></i>
                                </th>
                            </tr>
                        </thead>
                        <tbody class="small">
                            @foreach($data as $row)
                            <tr>
                                <td></td>
                                <td class="text-center" style="width: 50px">
                                    <img src="{!! asset('storage/services') . '/' . $row->image !!}" style="max-height: 40px" />
                                </td>
                                <td style="width: 200px">{!! $row->title !!}</td>
                                <td style="text-align: justify">{!! $row->description !!}</td>
                                <td style="width: 80px">
                                    @if($row->is_active == true)
                                        Active
                                    @elseif($row->is_active == false)
                                        Not Active
                                    @endif
                                </td>
                                <td style="width: 100px">{!! date('d-M-Y H:i', strtotime($row->created_at)) !!}</td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span>
                                            <span class="sr-only">Action</span>
                                        </button>
                                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                            <li>
                                                <a href="{!! route('service.show', $row->id) !!}"><i class="fa fa-eye"></i>Detail</a>
                                            </li>
                                            <li>
                                                <a href="{!! route('service.edit', $row->id) !!}"><i class="fa fa-edit"></i>Edit</a>
                                            </li>
                                            <li>
                                                <a href="#" data-toggle="modal" data-target="#delete-{!!$row->id!!}"><i class="fa fa-trash"></i>Delete</a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            <!-- Modal -->
                            <div class="modal fade modal-danger" id="delete-{!!$row->id!!}" tabindex="-1" role="dialog" aria-labelledby="delete">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        {!! Form::open([ 'route' => ['service.destroy', $row->id], 'method' => 'delete' ]) !!}
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                                    aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">Konfirmasi</h4>
                                        </div>
                                        <div class="modal-body">
                                            Apakah anda yakin akan menghapus service <b>{!! $row->title !!}</b>?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-outline">Hapus</button>
                                        </div>
                                        {!! Form::close() !!}
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function(){
            var t = $("#grid-service").DataTable({
                "columnDefs": [ 
                    {
                        "targets": 0,
                        "searchable": false,
                        "orderable": false,
                        "className": "dt-body-center",
                    },
                    {"targets": 1, "orderable": false},
                    {"targets": 3, "orderable": false},
                    {"targets": 6, "orderable": false},
                ],
                "order": [[5, 'desc']],
            });

            t.on('order.dt search.dt', function() {
                t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function(cell, i) {
                    cell.innerHTML = i+1;
                });
            }).draw();
        });
    </script>
@endsection

Resources/views/services/show.blade.php
@extends('cms::layouts.master')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="box-tools pull-right">
                        <a class="btn btn-sm btn-danger" href="{!! route('service.index') !!}">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body" style="min-height: 520px">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered table-hover">
                                <tr>
                                    <th width="30%">Title</th>
                                    <td>{!! $data->title !!}</td>
                                </tr>
                                <tr>
                                    <th>Description</th>
                                    <td>{!! $data->description !!}</td>
                                </tr>
                                <tr>
                                    <th>Image</th>
                                    <td>
                                        <img src="{!! asset('storage/services/' . $data->image) !!}" style="max-width: 300px; border-radius: 10px" />
                                    </td>
                                </tr>
                                <tr>
                                    <th>Order</th>
                                    <td>{!! $data->order !!}</td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td>{!! $data->is_active == true ? 'Active' : 'Disable' !!}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection