Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['web'])->group(function () {
    Route::name('cms.')->group(function() {

        Route::get('/', 'Frontend\HomeController@index')->name('home');
        Route::get('jobs', 'Frontend\HomeController@jobs')->name('job');
        Route::get('jobs/{slug}', 'Frontend\HomeController@jobsDetail')->name('job.detail');
        Route::get('clients', 'Frontend\HomeController@client')->name('client');
        Route::get('/info', 'Frontend\HomeController@info')->name('info');
        Route::get('/info/{id}', 'Frontend\HomeController@infoDetail')->name('info.detail');
        Route::get('contact', 'Frontend\HomeController@contactUs')->name('contact');
        Route::get('video/show/{id}', 'Frontend\HomeController@videoShow')->name('video');
        Route::get('test', 'Frontend\HomeController@test')->name('test');
        Route::get('test-result', 'Frontend\HomeController@testResult')->name('test.result');

    });
});

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('cms')->group(function() {
            Route::name('job.')->group(function() {
                Route::get('jobs', 'JobController@index')->name('index')->middleware('permission:cms-jobs-list');
                Route::get('jobs/create', 'JobController@create')->name('create')->middleware('permission:cms-jobs-create');
                Route::post('jobs/create', 'JobController@store')->name('store')->middleware('permission:cms-jobs-create');
                Route::get('jobs/{id}/edit', 'JobController@edit')->name('edit')->middleware('permission:cms-jobs-edit');
                Route::patch('jobs/{id}', 'JobController@update')->name('update')->middleware('permission:cms-jobs-edit');
                Route::delete('jobs/{id}', 'JobController@destroy')->name('destroy')->middleware('permission:cms-jobs-delete');
            });
            Route::name('slider.')->group(function() {
                Route::get('sliders', 'SliderController@index')->name('index');
                Route::get('sliders/create', 'SliderController@create')->name('create');
                Route::post('sliders/create', 'SliderController@store')->name('store');
                Route::get('sliders/{id}/show', 'SliderController@show')->name('show');
                Route::get('sliders/{id}/edit', 'SliderController@edit')->name('edit');
                Route::patch('sliders/{id}', 'SliderController@update')->name('update');
                Route::delete('sliders/{id}', 'SliderController@destroy')->name('destroy');
            });
            Route::name('info.')->group(function() {
                Route::get('info', 'InfoController@index')->name('index');
                Route::get('info/create', 'InfoController@create')->name('create');
                Route::post('info/create', 'InfoController@store')->name('store');
                Route::get('info/{id}/show', 'InfoController@show')->name('show');
                Route::get('info/{id}/edit', 'InfoController@edit')->name('edit');
                Route::patch('info/{id}', 'InfoController@update')->name('update');
                Route::delete('info/{id}', 'InfoController@destroy')->name('destroy');
            });

            Route::name('video.')->group(function() {
                Route::get('videos', 'VideoController@index')->name('index');
                Route::get('videos/create', 'VideoController@create')->name('create');
                Route::post('videos/create', 'VideoController@store')->name('store');
                Route::get('videos/{id}/show', 'VideoController@show')->name('show');
                Route::get('videos/{id}/edit', 'VideoController@edit')->name('edit');
                Route::patch('videos/{id}', 'VideoController@update')->name('update');
                Route::delete('videos/{id}', 'VideoController@destroy')->name('destroy');
            });

            Route::name('about.')->group(function() {
                Route::get('about', 'AboutUsController@index')->name('index');
                Route::get('about/{id}/edit', 'AboutUsController@edit')->name('edit');
                Route::patch('about/{id}', 'AboutUsController@update')->name('update');
            });

            Route::name('service.')->group(function() {
                Route::get('service', 'ServiceController@index')->name('index');
                Route::get('service/create', 'ServiceController@create')->name('create');
                Route::post('service/create', 'ServiceController@store')->name('store');
                Route::get('service/{id}/show', 'ServiceController@show')->name('show');
                Route::get('service/{id}/edit', 'ServiceController@edit')->name('edit');
                Route::patch('service/{id}', 'ServiceController@update')->name('update');
                Route::delete('service/{id}', 'ServiceController@destroy')->name('destroy');
            });

            Route::name('client.')->group(function() {
                Route::get('client', 'ClientController@index')->name('index');
                Route::get('client/create', 'ClientController@create')->name('create');
                Route::post('client/create', 'ClientController@store')->name('store');
                Route::get('client/{id}/edit', 'ClientController@edit')->name('edit');
                Route::patch('client/{id}', 'ClientController@update')->name('update');
                Route::delete('client/{id}', 'ClientController@destroy')->name('destroy');
            });

            Route::name('contact.')->group(function() {
                Route::get('contact', 'ContactController@index')->name('index');
                Route::get('contact/create', 'ContactController@create')->name('create');
                Route::post('contact/create', 'ContactController@store')->name('store');
                Route::get('contact/{id}/show', 'ContactController@show')->name('show');
                Route::get('contact/{id}/edit', 'ContactController@edit')->name('edit');
                Route::patch('contact/{id}', 'ContactController@update')->name('update');
                Route::delete('contact/{id}', 'ContactController@destroy')->name('destroy');
            });

            Route::name('setting.')->group(function() {
                Route::get('settings', 'SettingsController@index')->name('index');
            });
        });
    });
});

Entities/Slider.php
<?php

namespace Modules\CMS\Entities;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $table = 'cms_sliders';
    protected $fillable = [
        'is_text',
        'title',
        'caption_1',
        'caption_2',
        'caption_3',
        'is_image',
        'slider_img',
        'is_button',
        'btn_title',
        'btn_url',
        'order',
        'is_active'
    ];
}

Http/Controllers/SliderController.php
<?php

namespace Modules\CMS\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\CMS\Entities\Slider;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Redis;

class SliderController extends Controller
{
    protected $disk;

    public function __construct()
    {
        $this->disk = config('cms.disk');
    }
    
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $params['pageTitle']    = 'Sliders';
        $params['pageSubTitle'] = 'Index';
        $params['data']         = Slider::all();
        return view('cms::sliders.index', $params);
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $params['pageTitle']    = 'Sliders';
        $params['pageSubTitle'] = 'Create';
        return view('cms::sliders.create', $params);
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        try {
            $data['title']      = trim($request->title);
            $data['caption_1']  = trim($request->caption_1);
            $data['caption_2']  = trim($request->caption_2);
            $data['caption_3']  = trim($request->caption_3);
            $data['is_button']  = $request->is_button == 1 ? 1 : 0;
            $data['is_image']   = $request->is_image == 1 ? 1 : 0;
            $data['is_text']    = $request->is_text == 1 ? 1 : 0;
            $data['btn_title']  = trim($request->btn_title);
            $data['btn_url']    = trim($request->btn_url);
            $data['order']      = $request->order;
            $data['is_active']  = $request->is_active == 1 ? 1 : 0;
            
            if($request->hasFile('slider_img')) {
                $filename = 'slider-' . md5(date('Y-m-d').time());
                $path = 'cms/sliders/';
                $fullFilename = _upload_file($request->file('slider_img'), $filename, $path, $this->disk);
                $data['slider_img']   = $fullFilename;
            }
            Slider::create($data);
            return redirect(route('slider.index'))
				->with('success', trans('message.success_save'));
        } catch(\Exception $e) {
            return redirect(route('slider.index'))
				->with('error', trans('message.error_save'));
        }
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show($id)
    {
        $params['pageTitle']    = 'Sliders';
        $params['pageSubTitle'] = 'Detail';
        $params['data']         = Slider::findOrFail($id);
        return view('cms::sliders.show', $params);
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit($id)
    {
        $params['pageTitle']    = 'Sliders';
        $params['pageSubTitle'] = 'Edit';
        $params['data']         = Slider::findOrFail($id);
        return view('cms::sliders.edit', $params);
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(Request $request, $id)
    {
        try {
            $slider             = Slider::findOrFail($id);
            $data['title']      = trim($request->title);
            $data['caption_1']  = trim($request->caption_1);
            $data['caption_2']  = trim($request->caption_2);
            $data['caption_3']  = trim($request->caption_3);
            $data['is_button']  = $request->is_button == 1 ? 1 : 0;
            $data['is_image']   = $request->is_image == 1 ? 1 : 0;
            $data['is_text']    = $request->is_text == 1 ? 1 : 0;
            $data['btn_title']  = trim($request->btn_title);
            $data['btn_url']    = trim($request->btn_url);
            $data['order']      = $request->order;
            $data['is_active']  = $request->is_active == 1 ? 1 : 0;

            if($request->hasFile('slider_img')) {
                $filename = 'slider-' . md5(date('Y-m-d').time());
                $path = 'cms/sliders/';
                $fullFilename = _upload_file($request->file('slider_img'), $filename, $path, $this->disk);
                $data['slider_img']   = $fullFilename;
            }

            $slider->update($data);
            return redirect(route('slider.index'))
				->with('success', trans('message.success_edit'));
        } catch(\Exception $e) {
            return redirect(route('slider.index'))
				->with('error', trans('message.error_edit'));
        }
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy($id)
    {
        try {
            $data = Slider::findOrFail($id);
            if(!empty($data->slider_img)) {
                Storage::disk($this->disk)->delete('cms/sliders/' . $data->slider_img);
            }
            $data->delete();
            return redirect(route('slider.index'))
				->with('success', trans('message.success_delete'));
        } catch (\Exception $e) {
            return redirect(route('slider.index'))
				->with('error', trans('message.error_delete'));
        }
    }
}

Resources/views/sliders/create.blade.php
@extends('cms::layouts.master')

@section('content')
    {!! Form::open([ 'route' => 'slider.store', 'class' => 'form-horizontal', 'files' => true, 'autocomplete' => 'off' ]) !!}
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Slider</h3>
                        <div class="box-tools pull-right">
                            <a class="btn btn-sm btn-danger" href="{!! route('slider.index') !!}">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="box-body" style="min-height: 470px">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="" class="col-sm-4 control-label">Jenis Slider </label>
                                    <div class="col-sm-2">
                                        <div class="checkbox">
                                            <label>
                                                {!! Form::checkbox('is_image', true, true, ['id' => 'is_image']) !!} Gambar
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="checkbox">
                                            <label>
                                                {!! Form::checkbox('is_text', true, true, ['id' => 'is_text']) !!} Text
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-sm-2 is-button-group">
                                        <div class="checkbox">
                                            <label>
                                                {!! Form::checkbox('is_button', true, true, ['id' => 'is_button']) !!} Button
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                
                            </div>
                        </div>
                        <hr class="divider is-image" />
                        <div class="row is-image">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="slider_img" class="col-sm-4 control-label">Gambar <span class="required">*</span></label>
                                    <div class="col-sm-6">
                                        {!! Form::file('slider_img', [ 'class' => 'form-control', 'id' => 'slider_img', 'accept' => '.jpg,.png', 'required']) !!}
                                        <p class="help-block small">
                                            - best dimension 1080 x 400 <br>
                                            - max size 2 MB<br>
                                            - filetype jpg, png
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6"></div>
                        </div>
                        <hr class="divider is-text" />
                        <div class="row">
                            <div class="col-sm-6 is-text">
                                <div class="form-group">
                                    <label for="title" class="col-sm-4 control-label">Headline <span class="required">*</span></label>
                                    <div class="col-sm-6">
                                        {!! Form::text('title', null, [ 'class' => 'form-control', 'id' => 'title', 'maxlength' => 100, 'required']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="caption_1" class="col-sm-4 control-label">Caption 1 <span class="required">*</span></label>
                                    <div class="col-sm-6">
                                        {!! Form::text('caption_1', null, [ 'class' => 'form-control', 'id' => 'caption_1', 'maxlength' => 100, 'required']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="caption_2" class="col-sm-4 control-label">Caption 2</label>
                                    <div class="col-sm-6">
                                        {!! Form::text('caption_2', null, [ 'class' => 'form-control', 'maxlength' => 100]) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="caption_3" class="col-sm-4 control-label">Caption 3</label>
                                    <div class="col-sm-6">
                                        {!! Form::text('caption_3', null, [ 'class' => 'form-control', 'maxlength' => 100]) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 is-button">
                                <div class="form-group">
                                    <label for="btn_title" class="col-sm-4 control-label">Button Title</label>
                                    <div class="col-sm-6">
                                        {!! Form::text('btn_title', 'Lihat', [ 'class' => 'form-control', 'id' => 'btn_title']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="btn_url" class="col-sm-4 control-label">Button URL</label>
                                    <div class="col-sm-6">
                                        {!! Form::text('btn_url', '#', [ 'class' => 'form-control', 'id' => 'btn_url']) !!}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="divider" />
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="order" class="col-sm-4 control-label">Order</label>
                                    <div class="col-sm-3">
                                        {!! Form::number('order', 0, [ 'class' => 'form-control']) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="is_active" class="col-sm-4 control-label">Active? </label>
                                    <div class="col-sm-6">
                                        <div class="checkbox">
                                            <label>
                                                {!! Form::checkbox('is_active', true, true) !!} Yes
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="reset" class="btn btn-default">Cancel</button>
                        <button type="submit" class="btn btn-info pull-right" id="btn-save">Save</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            var isImage = $("#is_image");
            var isText  = $("#is_text");
            var isButton= $("#is_button");

            isImage.on('click', function() {
                if($(this).prop('checked') === true) {
                    $('.is-image').removeClass('hide');
                    $('#slider_img').prop('required', 'required');
                } else {
                    $('.is-image').addClass('hide');
                    $('#slider_img').prop('required', '');
                }
                showHideButton();
            });

            isText.on('click', function() {
                if($(this).prop('checked') === true) {
                    $('.is-text').removeClass('hide');
                    $('#title').prop('required', 'required');
                    $('#caption_1').prop('required', 'required');
                } else {
                    $('.is-text').addClass('hide');
                    $('#title').prop('required', '');
                    $('#caption_1').prop('required', '');
                }
                showHideButton();
            });

            isButton.click(function() {
                showHideIsButton($(this));
            });

            function showHideIsButton(btn) {
                if(btn.prop('checked') === true) {
                    $(".is-button").removeClass('hide');
                } else {
                    $(".is-button").addClass('hide');
                }
            }

            function showHideButton() {
                if(isImage.prop('checked') !== true && isText.prop('checked') !== true) {
                    $('.is-button-group').addClass('hide');
                    $('#btn-save').prop('disabled', 'disabled');
                    $(".is-button").addClass('hide');
                } else {
                    $('.is-button-group').removeClass('hide');
                    $('#btn-save').prop('disabled', '');
                    showHideIsButton(isButton);
                }
            }
            
        });
        
        $(function () {
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass: 'iradio_minimal-blue'
            });
        });
    </script>
@endsection

Resources/views/sliders/index.blade.php
@extends('cms::layouts.master')

@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="box-tools pull-right">
                        {{-- @can('slider-create') --}}
                        <a class="btn btn-sm btn-primary" href="{!! route('slider.create') !!}">
                            <i class="fa fa-plus"></i> Slider Baru
                        </a>
                        {{-- @endcan --}}
                    </div>
                </div>
                <div class="box-body" style="min-height: 520px">
                    <table id="grid-sliders" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th style="width: 5%">No.</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Caption</th>
                                <th>Status</th>
                                <th>Created</th>
                                <th class="text-center" style="width: 5%">
                                    <i class="fa fa-navicon"></i>
                                </th>
                            </tr>
                        </thead>
                        <tbody class="small">
                            @foreach($data as $row)
                            <tr>
                                <td></td>
                                <td>
                                    @if(!empty($row->slider_img))
                                        <img src="{!! _get_file($row->slider_img, '/cms/sliders/', config('cms.disk')) !!}" style="max-height: 40px" />
                                    @endif
                                </td>
                                <td>{!! $row->title !!}</td>
                                <td>{!! $row->caption_1 !!}</td>
                                <td>
                                    @if($row->is_active == true)
                                        Active
                                    @elseif($row->is_active == false)
                                        Not Active
                                    @endif
                                </td>
                                <td>{!! $row->created_at !!}</td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span>
                                            <span class="sr-only">Action</span>
                                        </button>
                                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                            <li>
                                                <a href="{!! route('slider.show', $row->id) !!}"><i class="fa fa-eye"></i>Detail</a>
                                            </li>
                                            <li>
                                                <a href="{!! route('slider.edit', $row->id) !!}"><i class="fa fa-edit"></i>Edit</a>
                                            </li>
                                            <li>
                                                <a href="#" data-toggle="modal" data-target="#delete-{!!$row->id!!}"><i class="fa fa-trash"></i>Delete</a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            <!-- Modal -->
                            <div class="modal fade modal-danger" id="delete-{!!$row->id!!}" tabindex="-1" role="dialog" aria-labelledby="delete">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        {!! Form::open([ 'route' => ['slider.destroy', $row->id], 'method' => 'delete' ]) !!}
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                                    aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">Konfirmasi</h4>
                                        </div>
                                        <div class="modal-body">
                                            Apakah anda yakin akan menghapus slider <b>{!! $row->title !!}</b>?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-outline">Hapus</button>
                                        </div>
                                        {!! Form::close() !!}
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function(){
            var t = $("#grid-sliders").DataTable({
                "columnDefs": [ 
                    {
                        "targets": 0,
                        "searchable": false,
                        "orderable": false,
                        "className": "dt-body-center",
                    },
                    {"targets": 1, "orderable": false},
                    {"targets": 6, "orderable": false},
                ],
                "order": [[5, 'desc']],
            });

            t.on('order.dt search.dt', function() {
                t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function(cell, i) {
                    cell.innerHTML = i+1;
                });
            }).draw();
        });
    </script>
@endsection