Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['web'])->group(function () {
    Route::name('cms.')->group(function() {

        Route::get('/', 'Frontend\HomeController@index')->name('home');
        Route::get('jobs', 'Frontend\HomeController@jobs')->name('job');
        Route::get('jobs/{slug}', 'Frontend\HomeController@jobsDetail')->name('job.detail');
        Route::get('clients', 'Frontend\HomeController@client')->name('client');
        Route::get('/info', 'Frontend\HomeController@info')->name('info');
        Route::get('/info/{id}', 'Frontend\HomeController@infoDetail')->name('info.detail');
        Route::get('contact', 'Frontend\HomeController@contactUs')->name('contact');
        Route::get('video/show/{id}', 'Frontend\HomeController@videoShow')->name('video');
        Route::get('test', 'Frontend\HomeController@test')->name('test');
        Route::get('test-result', 'Frontend\HomeController@testResult')->name('test.result');

    });
});

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('cms')->group(function() {
            Route::name('job.')->group(function() {
                Route::get('jobs', 'JobController@index')->name('index')->middleware('permission:cms-jobs-list');
                Route::get('jobs/create', 'JobController@create')->name('create')->middleware('permission:cms-jobs-create');
                Route::post('jobs/create', 'JobController@store')->name('store')->middleware('permission:cms-jobs-create');
                Route::get('jobs/{id}/edit', 'JobController@edit')->name('edit')->middleware('permission:cms-jobs-edit');
                Route::patch('jobs/{id}', 'JobController@update')->name('update')->middleware('permission:cms-jobs-edit');
                Route::delete('jobs/{id}', 'JobController@destroy')->name('destroy')->middleware('permission:cms-jobs-delete');
            });
            Route::name('slider.')->group(function() {
                Route::get('sliders', 'SliderController@index')->name('index');
                Route::get('sliders/create', 'SliderController@create')->name('create');
                Route::post('sliders/create', 'SliderController@store')->name('store');
                Route::get('sliders/{id}/show', 'SliderController@show')->name('show');
                Route::get('sliders/{id}/edit', 'SliderController@edit')->name('edit');
                Route::patch('sliders/{id}', 'SliderController@update')->name('update');
                Route::delete('sliders/{id}', 'SliderController@destroy')->name('destroy');
            });
            Route::name('info.')->group(function() {
                Route::get('info', 'InfoController@index')->name('index');
                Route::get('info/create', 'InfoController@create')->name('create');
                Route::post('info/create', 'InfoController@store')->name('store');
                Route::get('info/{id}/show', 'InfoController@show')->name('show');
                Route::get('info/{id}/edit', 'InfoController@edit')->name('edit');
                Route::patch('info/{id}', 'InfoController@update')->name('update');
                Route::delete('info/{id}', 'InfoController@destroy')->name('destroy');
            });

            Route::name('video.')->group(function() {
                Route::get('videos', 'VideoController@index')->name('index');
                Route::get('videos/create', 'VideoController@create')->name('create');
                Route::post('videos/create', 'VideoController@store')->name('store');
                Route::get('videos/{id}/show', 'VideoController@show')->name('show');
                Route::get('videos/{id}/edit', 'VideoController@edit')->name('edit');
                Route::patch('videos/{id}', 'VideoController@update')->name('update');
                Route::delete('videos/{id}', 'VideoController@destroy')->name('destroy');
            });

            Route::name('about.')->group(function() {
                Route::get('about', 'AboutUsController@index')->name('index');
                Route::get('about/{id}/edit', 'AboutUsController@edit')->name('edit');
                Route::patch('about/{id}', 'AboutUsController@update')->name('update');
            });

            Route::name('service.')->group(function() {
                Route::get('service', 'ServiceController@index')->name('index');
                Route::get('service/create', 'ServiceController@create')->name('create');
                Route::post('service/create', 'ServiceController@store')->name('store');
                Route::get('service/{id}/show', 'ServiceController@show')->name('show');
                Route::get('service/{id}/edit', 'ServiceController@edit')->name('edit');
                Route::patch('service/{id}', 'ServiceController@update')->name('update');
                Route::delete('service/{id}', 'ServiceController@destroy')->name('destroy');
            });

            Route::name('client.')->group(function() {
                Route::get('client', 'ClientController@index')->name('index');
                Route::get('client/create', 'ClientController@create')->name('create');
                Route::post('client/create', 'ClientController@store')->name('store');
                Route::get('client/{id}/edit', 'ClientController@edit')->name('edit');
                Route::patch('client/{id}', 'ClientController@update')->name('update');
                Route::delete('client/{id}', 'ClientController@destroy')->name('destroy');
            });

            Route::name('contact.')->group(function() {
                Route::get('contact', 'ContactController@index')->name('index');
                Route::get('contact/create', 'ContactController@create')->name('create');
                Route::post('contact/create', 'ContactController@store')->name('store');
                Route::get('contact/{id}/show', 'ContactController@show')->name('show');
                Route::get('contact/{id}/edit', 'ContactController@edit')->name('edit');
                Route::patch('contact/{id}', 'ContactController@update')->name('update');
                Route::delete('contact/{id}', 'ContactController@destroy')->name('destroy');
            });

            Route::name('setting.')->group(function() {
                Route::get('settings', 'SettingsController@index')->name('index');
            });
        });
    });
});

Entities/Jobs.php
<?php

namespace Modules\CMS\Entities;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Uuid as TraitsUuid;
use Illuminate\Support\Str;

class Jobs extends Model
{
    use TraitsUuid;

    protected $table = 'cms_jobs';

    public $incrementing    = false;
    
    protected $fillable = [
        'title', 'slug', 'desc', 'skills', 'location', 'degree_level', 'experience', 'company',
        'salary', 'expired', 'is_active'
    ];

    public function getJobExcerptAttribute()
    {
        return Str::words(strip_tags($this->desc), 20, ' ...');
    }
}

Http/Controllers/JobController.php
<?php

namespace Modules\CMS\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\CMS\Entities\Jobs;
use Illuminate\Support\Str;

class JobController extends Controller
{
    protected $pageTitle;
    protected $redirectTo;

    public function __construct()
    {
        $this->pageTitle = 'Jobs';
        $this->redirectTo= route('job.index');
    }
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        $params['pageSubTitle'] = 'Index';
        $params['data']         = Jobs::orderBy('created_at', 'DESC')->get();
        return view('cms::jobs.index', $params);
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $params['pageTitle']    = $this->pageTitle;
        $params['pageSubTitle'] = 'Create';
        return view('cms::jobs.create', $params);
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        try {
            $data['title']  = $request->title;
            $data['slug']   = $request->slug . '-' . Str::random(5);
            $data['desc']   = $request->description;
            $data['skills']     = $request->skills;
            $data['location']   = $request->location;
            $data['degree_level'] = $request->degree_level;
            $data['experience'] = $request->experience;
            $data['company']    = $request->company;
            $data['salary']     = !empty($request->salary) ? cleanNominal($request->salary) : null;
            $data['expired']    = !empty($request->expired) ? dateFormatYmd($request->expired) : null;
            $data['is_active']  = $request->is_active == null ? 0 : 1;

            Jobs::create($data);

            return redirect($this->redirectTo)
                ->with('success', trans('message.success_save'));
        } catch (\Exception $e) {
            return redirect($this->redirectTo)
                ->with('error', trans('message.error_save'));
        }
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show()
    {
        return view('cms::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit($id)
    {
        $params['pageTitle']    = $this->pageTitle;
        $params['pageSubTitle'] = 'Edit';
        $params['data'] = Jobs::findOrFail($id);
        return view('cms::jobs.edit', $params);
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(Request $request, $id)
    {
        try {
            $job    = Jobs::findOrFail($id);
            $data['title']  = $request->title;
            $data['slug']   = $request->slug;
            $data['desc']   = $request->description;
            $data['skills']     = $request->skills;
            $data['location']   = $request->location;
            $data['degree_level'] = $request->degree_level;
            $data['experience'] = $request->experience;
            $data['company']    = $request->company;
            $data['salary']     = !empty($request->salary) ? cleanNominal($request->salary) : null;
            $data['expired']    = !empty($request->expired) ? dateFormatYmd($request->expired) : null;
            $data['is_active']  = $request->is_active == null ? 0 : 1;

            $job->update($data);

            return redirect($this->redirectTo)
                ->with('success', trans('message.success_edit'));
        } catch (\Exception $ex) {
            return redirect($this->redirectTo)
                ->with('error', trans('message.error_edit'));
        }
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy($id)
    {
        try {
            $job    = Jobs::findOrFail($id);
            $job->delete();

            return redirect($this->redirectTo)
                ->with('success', trans('message.success_delete'));
        } catch (\Exception $ex) {
            return redirect($this->redirectTo)
                ->with('error', trans('message.error_delete'));
        }
    }
}

Resources/views/jobs/create.blade.php
@extends('cms::layouts.master')

@section('content')
    {!! Form::open([ 'route' => 'job.store', 'class' => 'form-horizontal', 'id' => 'form_jobs', 'autocomplete' => 'off' ]) !!}
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Jobs</h3>
                        <div class="box-tools pull-right">
                            <a class="btn btn-sm btn-danger" href="{!! route('job.index') !!}">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="box-body pad">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="title" class="col-sm-2 control-label">Title <span class="required">*</span></label>
                                    <div class="col-sm-8">
                                        {!! Form::text('title', null, [ 'class' => 'form-control', 'id' => 'title', 'maxlength' => 100, 'required', 'autofocus']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="slug" class="col-sm-2 control-label">Slug</label>
                                    <div class="col-sm-8">
                                        {!! Form::text('slug', null, [ 'class' => 'form-control', 'id' => 'slug', 'readonly']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="description" class="col-sm-2 control-label">Description <span class="required">*</span></label>
                                    <div class="col-sm-8">
                                        {!! Form::textarea('description', null, [ 'class' => 'form-control', 'id' => 'description', 'maxlength' => 1000, 'required']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="skills" class="col-sm-2 control-label">Skills</label>
                                    <div class="col-sm-8">
                                        {!! Form::textarea('skills', null, [ 'class' => 'form-control', 'id' => 'skills', 'maxlength' => 200]) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="location" class="col-sm-2 control-label">Location</label>
                                    <div class="col-sm-8">
                                        {!! Form::text('location', null, [ 'class' => 'form-control', 'id' => 'location']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="degree_level" class="col-sm-2 control-label">Degree Level</label>
                                    <div class="col-sm-8">
                                        {!! Form::text('degree_level', null, [ 'class' => 'form-control', 'id' => 'degree_level']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="experience" class="col-sm-2 control-label">Experience</label>
                                    <div class="col-sm-3">
                                        <div class="input-group">
                                            {!! Form::number('experience', null, [ 'class' => 'form-control', 'id' => 'experience', 'min' => 0]) !!}
                                            <span class="input-group-addon" id="basic-addon2">Tahun</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="company" class="col-sm-2 control-label">Company</label>
                                    <div class="col-sm-8">
                                        {!! Form::text('company', null, [ 'class' => 'form-control', 'id' => 'company']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="salary" class="col-sm-2 control-label">Salary</label>
                                    <div class="col-sm-3">
                                        {!! Form::text('salary', null, [ 'class' => 'form-control text-right number', 'id' => 'salary']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="expired" class="col-sm-2 control-label">Expired</label>
                                    <div class="col-sm-3">
                                        {!! Form::text('expired', null, [ 'class' => 'form-control datepicker', 'id' => 'expired']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="is_active" class="col-sm-2 control-label">Active? </label>
                                    <div class="col-sm-8">
                                        <div class="checkbox">
                                            <label>
                                                {!! Form::checkbox('is_active', true, true) !!} Yes
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="reset" class="btn btn-default">Cancel</button>
                        <button type="submit" class="btn btn-info pull-right">Save</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $("#description").wysihtml5({
                toolbar: {
                    size: "xs",
                    image: false,
                    blockquote: false
                }
            });
            $("#skills").wysihtml5({
                toolbar: {
                    size: "xs",
                    image: false,
                    blockquote: false
                }
            });
            $('.datepicker').datepicker({
                format: 'dd-mm-yyyy',
                autoclose: true,
                todayHighlight: true,
                weekStart: 1,
                startDate: new Date(),
                language: 'id'
            });
            $("#title").keyup(function(e) {
                let title = $(this).val();
                if(title.length > 0) {
                    let slug = slugThis(title);
                    $("#slug").val(slug);
                } else {
                    $("#slug").val('');
                }
            });
            $(".number").number(true, 0);

            $("#form_jobs").validate({
                errorElement: 'span',
                errorClass: 'help-block help-block-error small',
                focusInvalid: true,
                ignore: ":hidden:not(textarea)",
                rules: {
                    title: { required: true },
                    description: { required: true },
                    experience: { digits: true },
                    salary: { digits: true }
                },
                messages: {
                    title: { required: "harus diisi." },
                    description: { required: "harus diisi." },
                    experience: { digits: "harus angka." },
                    salary: { digits: "harus angka." }
                },
                highlight: function(element) {
                    $(element)
                        .closest('.form-group').addClass('has-error');
                },
                unhighlight: function(element) {
                    $(element)
                        .closest('.form-group').removeClass('has-error');
                },
                success: function(label) {
                    label
                        .closest('.form-group').removeClass('has-error');
                },
            });

            function slugThis(text) {
                return text
                    .toLowerCase()
                    .replace(/[^\w ]+/g,'')
                    .replace(/ +/g,'-');
            }
        });
        $(function () {
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass: 'iradio_minimal-blue'
            });
        });
    </script>
@endsection

Resources/views/jobs/index.blade.php
@extends('cms::layouts.master')

@section('content')

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"></h3>
                <div class="box-tools pull-right">
                    @can('cms-jobs-create')
                    <a class="btn btn-sm btn-primary" href="{!! route('job.create') !!}">
                        <i class="fa fa-plus"></i> Lowongan Baru
                    </a>
                    @endcan
                </div>
            </div>
            <div class="box-body" style="min-height: 520px">
                <div class="table-responsive">
                    <table id="grid-jobs" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th style="width: 5%">No.</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Skills</th>
                                <th>Location</th>
                                <th>Degree</th>
                                <th>Experience</th>
                                <th>Expired</th>
                                <th>Status</th>
                                <th>Created</th>
                                <th class="text-center" style="width: 5%">
                                    <i class="fa fa-navicon"></i>
                                </th>
                            </tr>
                        </thead>
                        <tbody class="small">
                            @foreach($data as $row)
                            <tr>
                                <td></td>
                                <td>{!! $row->title !!}</td>
                                <td>{!! $row->job_excerpt !!}</td>
                                <td>{!! $row->skills !!}</td>
                                <td>{!! $row->location !!}</td>
                                <td>{!! $row->degree_level !!}</td>
                                <td>{!! $row->experience !!}</td>
                                <td>{!! $row->expired !!}</td>
                                <td>
                                    @if($row->is_active == true)
                                        Active
                                    @elseif($row->is_active == false)
                                        Not Active
                                    @endif
                                </td>
                                <td>{!! $row->created_at !!}</td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span>
                                            <span class="sr-only">Action</span>
                                        </button>
                                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                            {{-- <li> --}}
                                                {{-- <a href="{!! route('slider.show', $row->id) !!}"><i class="fa fa-eye"></i>Detail</a> --}}
                                            {{-- </li> --}}
                                            @can('cms-jobs-edit')
                                            <li>
                                                <a href="{!! route('job.edit', $row->id) !!}"><i class="fa fa-edit"></i>Edit</a>
                                            </li>
                                            @endcan
                                            @can('cms-jobs-delete')
                                            <li>
                                                <a href="#" data-toggle="modal" data-target="#delete-{!!$row->id!!}"><i class="fa fa-trash"></i>Delete</a>
                                            </li>
                                            @endcan
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            <!-- Modal -->
                            <div class="modal fade modal-danger" id="delete-{!!$row->id!!}" tabindex="-1" role="dialog" aria-labelledby="delete">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        {!! Form::open([ 'route' => ['job.destroy', $row->id], 'method' => 'delete' ]) !!}
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                                    aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">Konfirmasi</h4>
                                        </div>
                                        <div class="modal-body">
                                            Apakah anda yakin akan menghapus Job <b>{!! $row->title !!}</b>?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-outline">Hapus</button>
                                        </div>
                                        {!! Form::close() !!}
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function(){
            var t = $("#grid-jobs").DataTable();
            $('.dataTables_scrollBody').css('height', '350px');
            t.on('order.dt search.dt', function() {
                t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function(cell, i) {
                    cell.innerHTML = i+1;
                });
            }).draw();
        });
    </script>
@endsection